### ISSUE TITLE
2.277.2 release prep

### ISSUE THREAD

**Issue by timja** [jenkins-infra/release#140]
# Jenkins 2.277.2 LTS release

## Release Lead

@MarkEWaite 

## Prep work

- [x] LTS baseline discussed and selected in the [Jenkins developers mailing list](https://groups.google.com/g/jenkinsci-dev)

- [x] Create or update release branch in [jenkinsci/jenkins](https://github.com/jenkinsci/jenkins), e.g. `stable-2.263`

- [x] Create or update release branch in [jenkins-infra/release](https://github.com/jenkins-infra/release), e.g. `stable-2.263`

- [x] Create or update release branch in [jenkinsci/packaging](https://github.com/jenkinsci/packaging), e.g. `stable-2.263`

- [x] ~~Create pull request to update [bom](https://github.com/jenkinsci/bom) to the weekly version that will be the base of the release line (strike this out for new point release)~~

- [x] ~~Create pull request to update [configuration-as-code integration tests](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/integrations/pom.xml) to the weekly version that will be the base of the release line (strike this out for new point release)~~

- [x] Review Jira and GitHub pull requests for additional LTS candidates, adding the 'lts-candidate' label, and ensure that all tickets are resolved in jira
    - [JENKINS-64972](https://issues.jenkins.io/browse/JENKINS-64972) - help buttons disabled when at top of draggable div. Fixed in [PR-5316](https://github.com/jenkinsci/jenkins/pull/5316), included in [Jenkins 2.283](https://www.jenkins.io/changelog/#v2.283), no reported regressions
    - [JENKINS-64931](https://issues.jenkins.io/browse/JENKINS-64931) - Deadlock with FutureImpl and Queue.  Fixed in [PR-5305](https://github.com/jenkinsci/jenkins/pull/5305), included in [Jenkins 2.283](https://www.jenkins.io/changelog/#v2.283), no reported regressions
    - [JENKINS-65186](https://issues.jenkins.io/browse/JENKINS-65186) - Reduce logging of renamed API endpoint.  Fixed in [PR-5207](https://github.com/jenkinsci/jenkins/pull/5207), included in [Jenkins 2.278 without a visible changelog entry](https://www.jenkins.io/changelog/#v2.278), no reported regressions
    - [JENKINS-62006](https://issues.jenkins.io/browse/JENKINS-62006) - Fix ClassNotFoundException on agents.  Fixed in [PR-5367](https://github.com/jenkinsci/jenkins/pull/5367), released in [Jenkins 2.285](https://www.jenkins.io/changelog/#v2.285), no reported regressions
    - skipped: [PR-5360](https://github.com/jenkinsci/jenkins/pull/5360) Use xstream 1.4.16 - upstream change not expected to impact Jenkins core
    - skipped: [PR-5350](https://github.com/jenkinsci/jenkins/pull/5350) and [PR-5334](https://github.com/jenkinsci/jenkins/pull/5334) Japanese translations
    - skipped: [PR-5341](https://github.com/jenkinsci/jenkins/pull/5341) - Accept negative numbers in INPUT.number - no visible malfunction in browser
    - skipped: [PR-5333](https://github.com/jenkinsci/jenkins/pull/5333) - Prevent form validation bugs from damaging page rendering - not flagged as `lts-candidate` by Daniel Beck (included in 2.283)
    - skipped: [PR-5300](https://github.com/jenkinsci/jenkins/pull/5300) - Bump spring-security-bom from 5.4.4 to 5.4.5 - a dependency revert, not expected to impact Jenkins use cases
    - skipped: [PR-5298](https://github.com/jenkinsci/jenkins/pull/5298) - Revert "Clean up VirtualFile..." - original PR is not in 2.277.1

- [x] Backporting announcement email - [script](https://github.com/jenkins-infra/backend-commit-history-parser/blob/master/bin/generate-backporting-announcement)

- [x] Update jira labels with the selected issues, e.g. `2.263.2-fixed`, `2.263.2-rejected`

- [x] Backport changes, create a local branch in jenkinsci/jenkins, run the [script](https://github.com/jenkins-infra/backend-commit-history-parser/blob/master/bin/list-issue-commits) to locate commits via jira ID, some manual work is required to locate them if the issue ID wasn't present at merge time, backport with `git cherry-pick -x $commit`

- [x] Open backporting PR with into-lts label and summary of changes in description from [script](https://github.com/jenkins-infra/backend-commit-history-parser/blob/master/bin/lts-candidate-stats)

- [x] Review ATH, bom and configuration-as-code integration tests results

- [x] Prepare [LTS changelog](https://www.jenkins.io/changelog-stable/) based on the [style guide](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/_STYLEGUIDE.adoc) using the [changelog generator](https://github.com/jenkinsci/core-changelog-generator/blob/master/README.md)

- [x] Prepare [LTS upgrade guide](https://www.jenkins.io/doc/upgrade-guide/) based on [previous upgrade guides](https://github.com/jenkins-infra/jenkins.io/tree/master/content/_data/upgrades)

## RC creation

- [x] Merge backporting PR in jenkinci/jenkins using a merge commit (do not squash)

- [x] Create or update release branch in [jenkins-infra/release](https://github.com/jenkins-infra/release), e.g. `stable-2.263`.

- [x] Create or update packaging branch in [jenkinsci/packaging]([jenkinsci/packaging](https://github.com/jenkinsci/packaging)), e.g. `stable-2.263`

- [x] ~~Run job on [release.ci.jenkins.io](https://release.ci.jenkins.io/job/core/job/stable-rc)~~

- [x] Publish a pre-release [Github release](https://github.com/jenkinsci/jenkins/releases), currently we don't have a changelog for RCs

- [x] Send announcement email

- [x] Check with security team that no security update is planned.  If a security update is planned, revise the checklist after the public pre-announcement to the [jenkinsci-advisories mailing list](https://groups.google.com/g/jenkinsci-advisories)

## LTS release

- [x] Publish changelog (one day prior to the release in case of a security update)

- [x] Run job on [release.ci.jenkins.io](https://release.ci.jenkins.io/) (packaging job ran on release.ci, build job ran in CERT).  Issues with websocket timeout for the Kubernetes agents changed to use websocket, but one successful run.

- [x] Check [LTS changelog](https://www.jenkins.io/changelog-stable/) is visible on the downloads site

- [x] Publish [GitHub release](https://github.com/jenkinsci/jenkins/releases) pointing to LTS changelog

- [x] Confirm [Datadog checks](https://p.datadoghq.com/sb/0Igb9a-e6849e5e019250ef5aaea3589297fe8b) are passing

- [x] Confirm the [Debian installer acceptance test](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/install-lts-debian-package/) is passing

- [x] Confirm the [Red Hat installer acceptance test](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/install-lts-redhat-rpm/) is passing

- [x] Adjust state of all [Jira issues](https://issues.jenkins.io/) fixed in the release (see the [changelog](https://www.jenkins.io/changelog-stable) for issue links)

- [x] Create pull request to update [bom](https://github.com/jenkinsci/bom) to the newly released version

- [x] Create pull request to update [configuration-as-code integration tests](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/integrations/pom.xml) to the newly released version

- [x] Run trusted.ci.jenkins.io [Docker image creation job](https://trusted.ci.jenkins.io:1443/job/Containers/job/Core%20Release%20Containers/job/master/)

- [x] [Update ci.jenkins.io](https://github.com/jenkins-infra/runbooks/tree/master/ci#upgrading-jenkins) to the new LTS release (note: repo is private, requires infra team membership)

**Comment by MarkEWaite** [comment]
Completed all items.  Needs an additional item in the checklist

[ ] Remove the `lts-candidate` label from [Jira issues resolved in the release](https://issues.jenkins.io/issues/?jql=labels%20%3D%20lts-candidate%20and%20status%20in%20(closed%2C%20resolved)%20ORDER%20BY%20status%20DESC%2C%20key%20ASC)
