### ISSUE TITLE
Automate updating bom to new LTS version

### ISSUE THREAD

**Issue by timja** [jenkins-infra/release#159]
https://github.com/jenkinsci/bom

See https://github.com/jenkinsci/helm-charts/blob/main/.github/workflows/sync-lts.yaml for a workflow that automates updating to a new LTS version

**Comment by NotMyFault** [comment]
updatecli takes care of that now.

**Comment by timja** [comment]
Nice, the main one missing is https://github.com/jenkins-infra/release/issues/158
