### ISSUE TITLE
Automate updating jcasc integration tests to new LTS version

### ISSUE THREAD

**Issue by timja** [jenkins-infra/release#160]
https://github.com/jenkinsci/configuration-as-code-plugin, see https://github.com/jenkinsci/configuration-as-code-plugin/pull/1601

See https://github.com/jenkinsci/helm-charts/blob/main/.github/workflows/sync-lts.yaml for a workflow that automates updating to a new LTS line

**Comment by olblak** [comment]
I am sure to understand. the release env is already using that image

**Comment by NotMyFault** [comment]
updatecli takes care of that now.
