### ISSUE TITLE
LTS 2.289.3

### ISSUE THREAD

**Issue by imonteroperez** [jenkins-infra/release#171]
# 2.289.3 LTS release

## Release Lead

@imonteroperez

## Prep work

- [ ] ~LTS baseline discussed and selected in the [Jenkins developers mailing list](https://groups.google.com/g/jenkinsci-dev)~

- [ ] ~Create or update release branch in [jenkinsci/jenkins](https://github.com/jenkinsci/jenkins), e.g. `stable-2.277`, use the [init-lts-line](https://github.com/jenkins-infra/backend-commit-history-parser/blob/master/bin/init-lts-line) script~

- [X] Create or update release branch in [jenkins-infra/release](https://github.com/jenkins-infra/release), e.g. `stable-2.277`. Created https://github.com/jenkins-infra/release/pull/172 @MarkEWaite @daniel-beck no permissions to add reviewers. Please take a look and merge.

- [ ] ~Create or update release branch in [jenkinsci/packaging](https://github.com/jenkinsci/packaging), e.g. `stable-2.277`~

- [ ] ~Create pull request to update [bom](https://github.com/jenkinsci/bom) to the weekly version that will be the base of the release line (strike this out for new point release)~

- [ ] ~Create pull request to update [configuration-as-code integration tests](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/integrations/pom.xml) to the weekly version that will be the base of the release line (strike this out for new point release)~

- [X] Review Jira and GitHub pull requests for additional LTS candidates, adding the 'lts-candidate' label, and ensure that all tickets are resolved in jira - Reviewed in: https://issues.jenkins.io/browse/JENKINS-65574?filter=12146, only one to backport `JENKINS-65574 - Build status animation is the wrong way` 

- [x] Backporting announcement email - [generate-backporting-announcement script](https://github.com/jenkins-infra/backend-commit-history-parser/blob/master/bin/generate-backporting-announcement) --> Asked for more additions on jenkins-dev ML. No answers yet. Only backport avaliable: https://github.com/jenkinsci/jenkins/pull/5622/commits/f73ce3198fd7319961313ea10aa2fc0f189ba47a

- [x] Update jira labels with the selected issues, e.g. `2.277.2-fixed`, `2.277.2-rejected` --> Updated to `2.289.3-fixed`

- [x] Backport changes, create a local branch in jenkinsci/jenkins, run the [list-issue-commits script](https://github.com/jenkins-infra/backend-commit-history-parser/blob/master/bin/list-issue-commits) to locate commits via jira ID, some manual work is required to locate them if the issue ID wasn't present at merge time, backport with `git cherry-pick -x $commit` --> Created https://github.com/jenkinsci/jenkins/pull/5622. 

- [x] Open backporting PR with into-lts label and summary of changes in description from [lts-candidate-stats script](https://github.com/jenkins-infra/backend-commit-history-parser/blob/master/bin/lts-candidate-stats) and the selected [Jira lts-candidates](https://issues.jenkins-ci.org/issues/?filter=12146)

- [x] Review ATH, bom and configuration-as-code integration tests results --> Reviewed ATH from: https://ci.jenkins.io/blue/organizations/jenkins/Core%2Fjenkins/detail/PR-5622/1/pipeline/97 seems failing based on:
```
[2021-07-15T07:57:28.923Z] process apparently never started in /home/jenkins/workspace/Core_jenkins_PR-5622/ath/testfirefoxjdk8@tmp/durable-1bf5112a
[2021-07-15T07:57:28.923Z] (running Jenkins temporarily with -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.LAUNCH_DIAGNOSTICS=true might make the problem clearer)
script returned exit code -2
```
@MarkEWaite would you mind confirming this is OK? based on the content of the backport PR I would assume it is fine (?)

Confirmed ok by @MarkEWaite 

- [x] Prepare [LTS changelog](https://www.jenkins.io/changelog-stable/) based on the [style guide](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/_STYLEGUIDE.adoc) using the [changelog generator](https://github.com/jenkinsci/core-changelog-generator/blob/master/README.md) --> Not able to perform this operation, getting the following error here:
```
imontero@imontero-cloudbees:~/desarrollo/cloudbees/imonteroperez/lts/jenkins(towards-2.289.3)$ ../core-changelog-generator/generate-jenkins-changelog.rb 2.289.3
Reading changelog configuration from 
Traceback (most recent call last):
	1: from ../core-changelog-generator/generate-jenkins-changelog.rb:34:in `<main>'
../core-changelog-generator/generate-jenkins-changelog.rb:34:in `read': no implicit conversion of nil into String (TypeError)
```
Seems env var named `CONFIG_PATH` is missed here: https://github.com/jenkinsci/core-changelog-generator/blob/master/generate-jenkins-changelog.rb#L32 

@MarkEWaite will generate the changelog by end of day July 22, 2021.

- [x] Prepare [LTS upgrade guide](https://www.jenkins.io/doc/upgrade-guide/) based on [previous upgrade guides](https://github.com/jenkins-infra/jenkins.io/tree/master/content/_data/upgrades) --> Ready on https://github.com/jenkins-infra/jenkins.io/pull/4463

## RC creation

- [x] Merge backporting PR in jenkinci/jenkins using a merge commit (do not squash)

- [ ] ~Create or update release branch in [jenkins-infra/release](https://github.com/jenkins-infra/release), e.g. `stable-2.277`.~

- [ ] ~Create or update packaging branch in [jenkinsci/packaging](https://github.com/jenkinsci/packaging), e.g. `stable-2.277`~

- [x] Deploy a release candidate built from your local machine, `mvn -e clean deploy -DskipTests=true`. --> Available in https://repo.jenkins-ci.org/ui/native/snapshots/org/jenkins-ci/main/jenkins-war/2.289.3-SNAPSHOT/

- [ ] ~Publish a pre-release [Github release](https://github.com/jenkinsci/jenkins/releases), currently we don't have a changelog for RCs~

- [x] Send announcement email, [example](https://groups.google.com/g/jenkinsci-dev/c/ox6SCyOQLuE/m/C-dsLZ4vBwAJ)

- [x] Check with security team that no security update is planned.  If a security update is planned, revise the checklist after the public pre-announcement to the [jenkinsci-advisories mailing list](https://groups.google.com/g/jenkinsci-advisories)

## LTS release

- [x] Publish changelog (one day prior to the release in case of a security update)

- [x] Run job on [release.ci.jenkins.io](https://release.ci.jenkins.io/blue/organizations/jenkins/core%2Fstable%2Frelease/branches/)

- [x] Check [LTS changelog](https://www.jenkins.io/changelog-stable/) is visible on the downloads site

- [x] Publish [GitHub release](https://github.com/jenkinsci/jenkins/releases) pointing to LTS changelog

- [x] Confirm [Datadog checks](https://p.datadoghq.com/sb/0Igb9a-e6849e5e019250ef5aaea3589297fe8b) are passing

- [x] Confirm the [Debian installer acceptance test](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/install-lts-debian-package/) is passing

- [x] Confirm the [Red Hat installer acceptance test](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/install-lts-redhat-rpm/) is passing

- [x] Adjust state of [Jira issues](https://issues.jenkins.io/) fixed in the release (see the [changelog](https://www.jenkins.io/changelog-stable) for issue links) and remove the `lts-candidate` label from [Jira issues resolved in the release](https://issues.jenkins.io/issues/?jql=labels%20%3D%20lts-candidate%20and%20status%20in%20(closed%2C%20resolved)%20ORDER%20BY%20status%20DESC%2C%20key%20ASC)

- [x] Create pull request to update [bom](https://github.com/jenkinsci/bom) to the newly released version -> https://github.com/jenkinsci/bom/pull/588

- [ ] ~Create pull request to update [configuration-as-code integration tests](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/integrations/pom.xml) to the newly released version~ -> https://github.com/jenkinsci/configuration-as-code-plugin/pull/1644 is done

- [x] #176

- [ ] [Update ci.jenkins.io](https://github.com/jenkins-infra/runbooks/tree/master/ci#upgrading-jenkins) to the new LTS release (note: repo is private, requires infra team membership) --> @MarkEWaite @daniel-beck do you mind to perform this? Thanks in advance!

**Comment by imonteroperez** [comment]
@MarkEWaite @daniel-beck would you mind generating/preparing LTS changelog ? I was not able to do that as mentioned in the related task item

> Not able to perform this operation, getting the following error here:
```
imontero@imontero-cloudbees:~/desarrollo/cloudbees/imonteroperez/lts/jenkins(towards-2.289.3)$ ../core-changelog-generator/generate-jenkins-changelog.rb 2.289.3
Reading changelog configuration from 
Traceback (most recent call last):
	1: from ../core-changelog-generator/generate-jenkins-changelog.rb:34:in `<main>'
../core-changelog-generator/generate-jenkins-changelog.rb:34:in `read': no implicit conversion of nil into String (TypeError)
```
> Seems env var named `CONFIG_PATH` is missed here: https://github.com/jenkinsci/core-changelog-generator/blob/master/generate-jenkins-changelog.rb#L32 @MarkEWaite @daniel-beck

**Comment by timja** [comment]
@imonteroperez file is here: https://github.com/jenkinsci/core-changelog-generator/blob/master/release-drafter.yml

just export that variable pointing to that file

**Comment by MarkEWaite** [comment]
> @MarkEWaite would you mind generating/preparing LTS changelog ? 

Happy to do that.  Should have it completed by end of day July 22, 2021.

**Comment by timja** [comment]
Looks like ci.jenkins.io isn't updated yet?

**Comment by bmunozm** [comment]
@timja can you update? Neither @imonteroperez or I have rights to do it :-(

**Comment by timja** [comment]
not right now but I've messaged in #jenkins-infra to see if someone else does

**Comment by timja** [comment]
@olblak has done it
