### ISSUE TITLE
Redhat Packaging Process: switch to createrepo_c (and bump version)

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/release#202]
### Feature Request

In order to build RPM (Redhat Linux series) packages for Jenkins, we are using a tool named `createrepo` (available from http://createrepo.baseurl.org/download/index.html).

This tools was packaged in Ubuntu 18.04 but isn't for Ubuntu 20.04, Debian and more recent distributions that we use for our agents.
https://answers.launchpad.net/createrepo/+question/690448 (It was python2 based, and Ubuntu20+ are Python3).

We need to switch this tool to the C version which is available at https://github.com/rpm-software-management/createrepo_c
that will be available with Ubuntu 21.04+, but also on Debian soon.

It implies us to bump the version because we are using 0.10.3, while createrepo_c starts at 0.15.

If we are OK with this, that could simplify the jenkins-infra/docker-packaging Dockerfile (that coiuld inherit from Inbound Agent latest Debian instead of sticking to Ubuntu:18.04.

**Comment by timja** [comment]
Sounds good to do but need to test it in some way or wait till the weekly after the security release I think
