### ISSUE TITLE
Add a password to the Digicert signing certificate

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/release#362]
As per https://github.com/jenkins-infra/release/blob/7a03f98eff839d4fed75ea96cf7bebbc963e3a91/utils/release.bash#L79-L81, the `pfx` file does not have a password.

However, this comment was made in 2020. We are 2023, and as per https://learn.microsoft.com/en-us/azure/key-vault/certificates/tutorial-import-certificate?tabs=azure-portal, password for `pfx`certificate *seems* supported.

As an additional layer of security, we should be able to use a password (instead of converting pfx to pem for adding one).

Discovered while working on https://github.com/jenkins-infra/helpdesk/issues/3323

**Comment by timja** [comment]
You might want to read the docs a bit closer ^.^

> Once the certificate file is successfully imported, key vault will remove that password.

**Comment by dduportal** [comment]
🤦 correct, thanks for pointing it out 😅

Gotta close the issue then 👍
