### ISSUE TITLE
Weekly release failed due to master branch commits during build

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/release#387]
### Your checklist for this issue

The release should complete successfully even if commits arrived on the release branch while the release was being built.

* [x] Weekly release should complete successfully even if commits arrive on the release branch while the release is being built
* [x] LTS release should fail if commits arrive on the release branch while the release is being built

### Feature Request

Based on the experience with the Jenkins 2.409 release, it seems that if a commit arrives on the release branch after the build has started but before the build has completed, then when maven attempts to push the commits to the remote repository, it will fail with a git conflict.  In the 2.409 case, a pull request had been merged while the build was running.

**Comment by daniel-beck** [comment]
> I _think_ the solution to this issue is to change
> 
> https://github.com/jenkins-infra/release/blob/4bf463fcf447618532fdb7c1761e2ae5565e81fb/utils/release.bash#L391
> to `git pull --rebase`. That should not affect the tag that has been already created (and will be pushed in the next line and used during the `release:perform` phase), but it should have the desirable effect of allowing commits that have been pushed in the meantime to not break the push in the next line.

That'd remove the actual released commits from the history as they're being rebased on top of what is pulled.

Creating a merge commit (as KK used to do in this situation) seems preferable. Something like `git fetch <remote> && git merge --no-edit <remote>/master`?

**Comment by basil** [comment]
Agreed, a merge commit sounds preferable.

**Comment by daniel-beck** [comment]
>  LTS release should complete successfully even if commits arrived on the release branch while the release was being built

LTS have content that is planned and agreed on in advance. Something went very wrong there if commits arrive during the release process, so that should in fact not complete successfully / should not deploy Maven artifacts. Wrong content is worse than a few hours delay.

**Comment by basil** [comment]
I am told this week's release was delayed due to changes being merged while the build is running.

**Comment by basil** [comment]
> Something like `git fetch <remote> && git merge --no-edit <remote>/master`?

Yes, suggest e.g.:

```bash
diff --git a/utils/release.bash b/utils/release.bash
index ce5d8ed..a0a1e0b 100755
--- a/utils/release.bash
+++ b/utils/release.bash
@@ -388,7 +388,8 @@ function pushCommits() {
 	# Ensure we use ssh credentials
 	git config --get remote.origin.url
 	sed -i 's#url = https://github.com/#url = git@github.com:#' .git/config
-	git pull
+	git fetch origin
+	git merge --no-edit "origin/${RELEASE_GIT_BRANCH}"
 	git push origin "HEAD:${RELEASE_GIT_BRANCH}" "${RELEASE_SCM_TAG}"
 }

```

**Comment by MarkEWaite** [comment]
I think that is a very good recommendation.

The failure message in the log offers an alternate path.  The failure message is:

```bash
+ sed -i 's#url = https://github.com/#url = git@github.com:#' .git/config
+ git pull
From github.com:jenkinsci/jenkins
    004e72746a..5da5ac7e62  master       -> origin/master
    2bc5292feb..96dc95a55e  stable-2.426 -> origin/stable-2.426
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
```

I don't think that `git config pull.rebase false` is as clear as `git fetch origin`.
